// SPDX-License-Identifier: MIT
// Copyright (c) 2026 The Bento authors
// What a fresh bento/spaces file opens with.
//
// The brief slides set: the product demo, the launch asset and the feature
// tour in one — every claim it makes is proven by the feature making it. So
// the page that describes links CONTAINS a link, the page about sharing is
// reachable only through one, and the limits page says the awkward things out
// loud rather than letting them be discovered.
//
// Which is why the TRACKER is here. It shipped with none of this: a fresh space
// opened on the notes tour, and the board, the fields and ⌘⇧I existed only for
// someone who already knew to look for them. A feature the starter does not
// demonstrate is a feature the starter denies.

import { FORMAT, FORMAT_VERSION, defaultTheme, type SpacesDoc, type Block, type Page } from './model.ts'
import { DEFAULT_FIELDS, ISSUE_FIELDS, propBlock } from './fields.ts'

const nextId = (): string => `sd-${(seq++).toString(36)}`

const b = (type: string, html = '', extra: Partial<Block> = {}): Block =>
  ({ id: nextId(), type, html, ...extra })

let seq = 0

/**
 * A starter ISSUE — a page whose first blocks are its fields.
 *
 * Built through `propBlock` and `DEFAULT_FIELDS` rather than written out as
 * literal blocks, for one reason: `value` and the readable `html` beside it
 * have to agree, and hand-written starter blocks are exactly the copy that
 * silently stops agreeing the first time an option is renamed. The starter is
 * the one document every new space is judged by; it should be generated by the
 * same rule the app enforces at runtime.
 *
 * Seeded from `ISSUE_FIELDS`, so a starter issue carries the same fields as one
 * made with ⌘⇧I or `bento.newIssue()` — an issue here missing `assignee` would
 * be an issue with nowhere to put one.
 */
function issue(title: string, parent: string, values: Record<string, string>, body: string): Page {
  const props = DEFAULT_FIELDS
    .filter((f) => ISSUE_FIELDS.includes(f.key))
    .map((f) => propBlock(f, values[f.key] ?? f.def ?? '', nextId()))
  return { id: nextId(), title, parent, blocks: [...props, b('p', body)] }
}

/** Deterministic ids: a generator must emit the same document twice. */
export function starterDoc(): SpacesDoc {
  seq = 0
  const P = {
    home: 'sd-home',
    links: 'sd-links',
    writing: 'sd-writing',
    limits: 'sd-limits',
    tracker: 'sd-tracker',
    inbox: 'sd-inbox',
  }

  // the toggle is built first so its child can name its REAL id — a parent
  // pointing at an id that does not exist would render the child at top level
  const toggle = b('toggle', 'A toggle — click the triangle', { open: true })
  const callout = b('callout', 'A callout. Click the mark to make it a note, a tip, a warning.', { tone: 'tip' })

  return {
    format: FORMAT,
    version: FORMAT_VERSION,
    docId: '', // minted at boot; a template mints a fresh one every open
    title: 'My space',
    home: P.home,
    theme: defaultTheme(),
    pages: [
      {
        id: P.home,
        title: 'Welcome',
        icon: 'compass',
        blocks: [
          b('p', 'This whole space — every page, the editor, the search — is <b>one HTML file</b>. No account, no server, nothing installed.'),
          b('h2', 'Try it'),
          b('todo', 'Type something on this line', { done: false }),
          b('todo', 'Press <code>⏎</code> to make a new block, <code>Tab</code> to indent it', { done: false }),
          b('todo', 'Press <code>/</code> on an empty line for headings, lists, quotes and code', { done: false }),
          b('todo', 'Press <code>⌘K</code> to search every page at once', { done: false }),
          b('p', 'Then press <code>⌘S</code>. The file on your disk now contains everything you just wrote.'),
          b('h2', 'What is here'),
          b('p', 'Four pages, and each one demonstrates the thing it describes:'),
          b('bullet', '<a href="#p/sd-links">Pages and links</a> — how a space holds more than one page'),
          b('bullet', '<a href="#p/sd-writing">Writing</a> — the blocks you can make'),
          b('bullet', '<a href="#p/sd-tracker">Tracker</a> — the same pages, on a board'),
          b('bullet', '<a href="#p/sd-limits">Sharing &amp; limits</a> — what this file can and cannot do'),
          b('p', 'The sidebar holds the whole tree. Drag a page onto another to nest it.'),
        ],
      },
      {
        id: P.links,
        title: 'Pages and links',
        icon: 'link',
        blocks: [
          b('p', 'A space is a <b>tree of pages</b>, not a single scroll. New page: the ＋ in the sidebar, or <code>⌘⌥N</code>.'),
          b('h2', 'Linking'),
          b('p', 'Type <code>[[</code> anywhere to search your pages and drop a link in. If the page does not exist yet, the picker offers to make it.'),
          b('p', 'That link back to <a href="#p/sd-home">Welcome</a> was made exactly that way.'),
          b('h2', 'Backlinks'),
          b('p', 'Scroll to the bottom of any page and it tells you what links <i>to</i> it. Nothing to maintain — it is derived from the links themselves every time the page opens.'),
          b('p', 'This page links to <a href="#p/sd-writing">Writing</a>, so Writing lists this page underneath.'),
          b('h2', 'Why one file'),
          b('p', 'Links are page ids inside this document, so they resolve with the wifi off, from an email attachment, on a phone, and in ten years. A link between separate files could not do any of that.'),
        ],
      },
      {
        id: P.writing,
        title: 'Writing',
        icon: 'pen',
        blocks: [
          b('p', 'Markdown shortcuts convert as you type them.'),
          b('h2', 'Headings'),
          b('p', 'Type <code># </code>, <code>## </code> or <code>### </code> at the start of a line.'),
          b('h2', 'Lists'),
          b('bullet', '<code>- </code> makes a bullet'),
          b('bullet', 'and <code>Tab</code> nests it'),
          b('number', '<code>1. </code> makes a numbered list'),
          b('todo', '<code>[] </code> makes a checkbox', { done: false }),
          b('h2', 'Blocks that are not text'),
          b('quote', 'A quote — type <code>&gt; </code>.'),
          b('code', 'const space = oneFile\n// type ``` and a SPACE to make a code block', { lang: 'js' }),
          callout,
          b('p', 'Press <code>⏎</code> in a callout and the next line goes inside it. Empty line, <code>⌫</code>, and you are out.', { parent: callout.id }),
          b('code',
            '// type ```js and a space — the language is yours to pick\n' +
            'const space = { file: 1, pages: 5 }\n' +
            'console.log(`one file, ${space.pages} pages`)',
            { lang: 'js' }),
          b('p', 'Hover a code block to see — and change — its language.'),
          toggle,
          b('p', 'Anything indented under a toggle folds away with it.', { parent: toggle.id }),
          b('divider'),
          b('p', 'Inline: <b>⌘B</b>, <i>⌘I</i>, <u>⌘U</u>.'),
          b('h2', 'Lines that work things out'),
          b('p', 'End a line with <code>=</code> and it answers. The answer is never stored — change a number above and every line below follows.'),
          b('p', 'budget = 2400'),
          b('p', 'flights = 780'),
          b('p', 'budget - flights ='),
          b('p', '20% of budget ='),
          b('p', '940 km in miles ='),
          b('p', 'today + 3 weeks ='),
          b('p', 'It understands arithmetic, percentages, units, dates, times, names you define, and <code>sum above</code>. Type a sum without the <code>=</code> and it shows you the answer first — press <code>Tab</code> to keep it.'),
        ],
      },
      {
        id: P.limits,
        title: 'Sharing & limits',
        icon: 'scale',
        blocks: [
          b('p', 'Worth knowing before you rely on this.'),
          b('h2', 'Sharing is per file'),
          b('p', 'Sending someone this file sends them <b>the whole space</b> — every page, including any you archived. There is no per-page permission, because there is no server to enforce one.'),
          b('h2', 'Saving'),
          b('p', 'On Chrome and Edge, <code>⌘S</code> writes back to the file you opened. Everywhere else — Safari, Firefox, and every browser on iOS — the browser gives a page no way to write to its own file, so each save downloads a <b>new copy</b>. That is a browser limitation, not a setting.'),
          b('h2', 'Two people, two files'),
          b('p', 'If two people edit their own copy at the same time, there is no merge. They are two files. Live collaboration is coming; until it does, this is the honest position.'),
          b('h2', 'Size'),
          b('p', 'Text is essentially free — hundreds of pages of prose stay a small file. Images are what make it big, because they travel inside it.'),
        ],
      },
      {
        id: P.tracker,
        title: 'Tracker',
        icon: 'board',
        blocks: [
          b('p', 'An <b>issue is a page</b>. The cards below are the pages nested under this one — open one and you are in a document you can write anything in, with its fields along the top.'),
          b('p', 'Nothing here is a second kind of thing: issues search, link, print, export and back-link like every other page. A page becomes an issue when it has a status, and stops being one when it does not.'),
          b('view', 'Issues', { layout: 'board', groupBy: 'status' }),
          b('h2', 'Making them'),
          b('p', '<code>⌘⇧I</code> makes an issue. The tag button in the toolbar turns the page you are already on into one — useful when a note turns out to be work.'),
          b('p', 'Drag a card to another column to change its status. <b>Open only</b> hides what is done; <b>Filter</b> narrows by any field.'),
        ],
      },
      ...[
        issue('Open this card — it is an ordinary page', P.tracker,
          { status: 'doing', priority: 'high' },
          'You are in it. The row above is fields; everything from here down is a page — write notes, paste an image, nest a toggle. That is the whole trick: the tracker did not invent a new thing to hold work in, it put fields on the thing you already had.'),
        issue('Drag me to another column', P.tracker,
          { status: 'todo', priority: 'medium' },
          'Dragging a card writes the new status onto this page. Go the other way too: change the field at the top and watch the card move on the board.'),
        issue('Press ⌘⇧I to make your own', P.tracker,
          { status: 'todo', priority: 'urgent' },
          'A new issue arrives with status, priority, assignee and estimate already on it, and the caret in the body waiting for you.'),
        issue('Delete all of this once you have seen it', P.tracker,
          { status: 'backlog' },
          'These five are a demonstration, not a template. Delete them and the board is empty and yours — it shows whatever pages in this space have a status, wherever they live in the tree.'),
        issue('This one is finished', P.tracker,
          { status: 'done' },
          'Done and cancelled are <i>phases</i>, not just names, which is what lets <b>Open only</b> mean something without anyone configuring a filter.'),
      ],
      {
        id: P.inbox,
        title: 'Inbox',
        icon: 'inbox',
        blocks: [
          b('p', 'A page to throw things into before they are worth filing.'),
          b('p', ''),
        ],
      },
    ],
  }
}
