#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 The Bento authors
//
// Conformance test for the platform's splice path — HEAD + escape(json) +
// TAIL, generated by platform/build/split-shell.mjs and consumed by
// platform/worker/src/splice.ts at request time.
//
// This mirrors scripts/shell-gate.mjs's invariants (splice contract intact,
// data block escaped and lossless, adversarial payload survives, unescaped
// payload is CAUGHT as a negative control) but exercises the platform's own
// split shape rather than the live-DOM clone/save path, since a Worker has
// no DOM. Run after every `node platform/build/split-shell.mjs`:
//
//   node platform/worker/test/splice.test.mjs

import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const generatedPath = join(here, '..', 'src', 'generated', 'shell.ts')

let SHELL_HEAD, SHELL_TAIL
try {
  const src = readFileSync(generatedPath, 'utf8')
  // Pull the two string-literal exports out of the generated .ts without a
  // TS toolchain — they're plain JSON.stringify'd string literals.
  const grab = (name) => {
    const marker = `export const ${name} = `
    const start = src.indexOf(marker)
    if (start < 0) throw new Error(`${name} not found in generated shell.ts`)
    const quoteStart = start + marker.length
    if (src[quoteStart] !== '"') throw new Error(`${name} is not a quoted string literal`)
    // Walk to the literal's real closing quote (respecting \" escapes) rather
    // than handing the whole file tail to JSON.parse, which requires the
    // ENTIRE remaining text to be valid JSON, not just a leading string.
    let i = quoteStart + 1
    while (i < src.length) {
      if (src[i] === '\\') { i += 2; continue }
      if (src[i] === '"') { i += 1; break }
      i += 1
    }
    return JSON.parse(src.slice(quoteStart, i))
  }
  SHELL_HEAD = grab('SHELL_HEAD')
  SHELL_TAIL = grab('SHELL_TAIL')
} catch (e) {
  console.error(`✗ could not read ${generatedPath}: ${e.message}`)
  console.error('  run `node platform/build/split-shell.mjs` first (after building the slides shell)')
  process.exit(2)
}

const SCRIPT_CLOSE = '</scr' + 'ipt>'
const DOC_BLOCK_RE = /<script type="application\/bento\+json" id="bento-doc">[\s\S]*?<\/script>/

const escapeBlockText = (json) => json.replace(/</g, '\\u003c')
const splice = (doc) => SHELL_HEAD + escapeBlockText(JSON.stringify(doc)) + SHELL_TAIL

let failures = 0
const check = (name, fn) => {
  try {
    fn()
    console.log(`  ✓ ${name}`)
  } catch (e) {
    failures++
    console.error(`  ✗ ${name}: ${e.message}`)
  }
}
const assert = (cond, msg) => {
  if (!cond) throw new Error(msg)
}

console.log('platform splice conformance')

check('HEAD ends with the #bento-doc opening tag', () => {
  assert(SHELL_HEAD.trimEnd().endsWith('id="bento-doc">'), 'HEAD does not end at the opening tag')
})

check('TAIL starts with the closing tag', () => {
  assert(SHELL_TAIL.trimStart().startsWith(SCRIPT_CLOSE), 'TAIL does not start at the closing tag')
})

check('script tag balance holds after splice', () => {
  const html = splice({ format: 'bento/slides', title: 'Test deck' })
  const opens = (html.match(/<script[\s>]/g) ?? []).length
  const closes = html.split(SCRIPT_CLOSE).length - 1
  assert(opens === closes, `${opens} opens vs ${closes} closes`)
})

check('#bento-doc is extractable and round-trips losslessly', () => {
  const doc = { format: 'bento/slides', title: 'Round trip', n: 42, nested: { a: [1, 2, 3] } }
  const html = splice(doc)
  const block = html.match(DOC_BLOCK_RE)
  assert(block, 'block not found')
  const inner = block[0].replace(/^<script[^>]*>/, '').replace(/<\/script>$/, '').trim()
  assert(!inner.includes('<'), 'unescaped "<" survived into the block')
  const parsed = JSON.parse(inner)
  assert(JSON.stringify(parsed) === JSON.stringify(doc), 'doc did not round-trip losslessly')
})

check('adversarial content cannot break out of the block', () => {
  const doc = {
    format: 'bento/slides',
    hostile: '</script><script>alert(1)</script>',
    forgedOpen: '<script type="application/bento+json" id="bento-doc">{"hijacked":true}</script>',
    entities: '<!-- --> <![CDATA[ & " \' ` \\',
    rtl: 'مرحبا — שלום 🎌',
    separators: 'a b c',
  }
  const html = splice(doc)
  const opens = (html.match(/<script[\s>]/g) ?? []).length
  const closes = html.split(SCRIPT_CLOSE).length - 1
  assert(opens === closes, `script tag imbalance after adversarial splice: ${opens}/${closes}`)

  const block = html.match(DOC_BLOCK_RE)[0]
  const inner = block.replace(/^<script[^>]*>/, '').replace(/<\/script>$/, '').trim()
  const parsed = JSON.parse(inner)
  assert(JSON.stringify(parsed) === JSON.stringify(doc), 'adversarial doc did not round-trip losslessly')

  // exactly one #bento-doc block exists after the splice — the forged opening
  // tag riding inside the escaped JSON must not be extractable as a second one
  const allDocBlocks = html.match(new RegExp(DOC_BLOCK_RE.source, 'g')) ?? []
  assert(allDocBlocks.length === 1, `expected exactly one #bento-doc block, found ${allDocBlocks.length}`)
})

check('NEGATIVE CONTROL: skipping the escape lets injected markup go live', () => {
  // Prove the escape is load-bearing, not decorative: splice the SAME hostile
  // doc with and without escapeBlockText and show the difference is exactly
  // "injected markup becomes live HTML" vs. "stays inert JSON text".
  const hostileDoc = { format: 'bento/slides', hostile: '</script><img src=x onerror=alert(1)>' }
  const unescapedHtml = SHELL_HEAD + JSON.stringify(hostileDoc) + SHELL_TAIL
  const escapedHtml = splice(hostileDoc)

  assert(
    unescapedHtml.includes('<img src=x onerror=alert(1)>'),
    'sanity check failed: the unescaped form should demonstrate the injection escaping the script block',
  )
  assert(
    !escapedHtml.includes('<img src=x onerror=alert(1)>'),
    'the payload appears as live markup even WITH escapeBlockText applied — escape is broken',
  )
})

console.log(failures ? `\n${failures} check(s) failed` : '\nall checks passed')
process.exit(failures ? 1 : 0)
